# Vehicle Type

What sort of vehicles are involved in these crashes?

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib._color_data import BASE_COLORS, TABLEAU_COLORS, CSS4_COLORS, XKCD_COLORS
from crash_data_analysis import CrashDataAnalysis

In [2]:
cda = CrashDataAnalysis()
df = cda.crash_dataframe(verbose=True, all_columns=True)

Reading file: data/denver_crashes_2023_01_19__14_31.csv
Max timestamp: Wed Jan 18, 6:48 PM (0.86 days ago)
Deadly crashes this year: 3

In [3]:
df.TU1_VEHICLE_TYPE.unique()

array(['PASSENGER CAR/VAN', 'SUV', '  ', 'HIT AND RUN UNKNOWN',
       'PICKUP TRUCK/UTILITY VAN', 'NON-SCHOOL BUS',
       'PICKUP TRUCK/UTILITY VAN WITH TRAILIER', 'VEHICLE OVER 10000 LBS',
       'OTHER', 'BICYCLE', 'MOTOR HOME', 'TRANSIT BUS', 'SCHOOL BUS',
       'MOTORCYCLE', 'MOTORIZED BICYCLE',
       'PASSENGER CAR/VAN WITH TRAILER', 'SUV WITH TRAILER',
       'FARM EQUIPMENT', 'LIGHT RAIL', 'UNDER INVESTIGATION', 'UNK', '0',
       'Passenger Car/Passenger Van', 'Pickup Truck/Utility Van',
       'Medium/Heavy Trucks GVWR/GCWR between 10,001 and 16,000', nan,
       'Motorcycle', 'Unknown (Hit and Run Only)', 'Transit Bus',
       'Medium/Heavy Trucks GVWR/GCWR 16,001 and over',
       'Other Vehicle Type (Describe in Narative)',
       'School Bus (all school buses)', 'Autocycle',
       'Working Vehicle/Equipment', 'Motor Home',
       'Non-School Bus (9 occupants or more including driver) in commerce',
       'Low Speed Vehicle', 'Off Highway Vehicle/ATV', 'Farm Equipment'],
      dtype=object)

In [4]:
df.TU1_VEHICLE_MOVEMENT.unique()

array(['GOING STRAIGHT', 'MAKING LEFT TURN', 'MAKING U-TURN', '  ',
       'ENTERING/LEAVING PARKED POSITION', 'OTHER', 'BACKING', 'SLOWING',
       'MAKING RIGHT TURN', 'CHANGING LANES', 'STOPPED IN TRAFFIC',
       'PASSING', 'SPUN OUT OF CONTROL', 'WEAVING', 'PARKED',
       'AVOIDING OBJECT IN ROADWAY', 'DROVE WRONG WAY',
       'UNDER INVESTIGATION', '021', '18', '00', 'Going Straight',
       'Making Left Turn', 'Changing Lanes',
       'Other (Describe in Narrative)', nan,
       'Entering/Leaving Parked Position', 'Making Right Turn', 'Backing',
       'Traveled Wrong Way', 'Entering Traffic Way/Merge',
       'Making U-Turn', 'Slowing', 'Weaving', 'Parked',
       'Stopped in Traffic', 'Negotiating a Curve', 'Out of Control',
       'Swerve/Avoidance', 'Passing'], dtype=object)

In [5]:
# df['at_fault_vehicle'] = df['TU1_VEHICLE_TYPE']

# otherize = ['  ', '0', 'UNK']
# for v in otherize:
#     df.loc[df.TU1_VEHICLE_TYPE == v, 'at_fault_vehicle'] = 'Other'

In [6]:
df['TU1_VEHICLE_TYPE_UPPER'] = df['TU1_VEHICLE_TYPE'].str.upper()

vehicle_type_mapping = {
    '  ': 'Other'
    , '0': 'Other'
    , 'UNK': 'Other'
    , 'OTHER VEHICLE TYPE (DESCRIBE IN NARATIVE)': 'Other'
    , 'OTHER': 'Other'
    , 'SUV WITH TRAILER': 'SUV'
    , 'PASSENGER CAR/VAN': 'Passenger Car/Van'
    , 'PASSENGER CAR/VAN WITH TRAILER': 'Passenger Car/Van'
    , 'PASSENGER CAR/PASSENGER VAN': 'Passenger Car/Van'
    , 'SCHOOL BUS': 'Bus'
    , 'SCHOOL BUS (ALL SCHOOL BUSES)': 'Bus'
    , 'TRANSIT BUS': 'Bus'
    , 'HIT AND RUN UNKNOWN': 'Unknown (Hit and Run Only)'
    , 'PICKUP TRUCK/UTILITY VAN': 'Pickup Truck'
    , 'PICKUP TRUCK/UTILITY VAN WITH TRAILIER': 'Pickup Truck'
    , 'VEHICLE OVER 10000 LBS': 'Semi Truck'
    , 'MOTORCYCLE': 'Motorcycle'
    , 'BICYCLE': 'Bicycle'
    , 'UNDER INVESTIGATION': 'Under Investigation'
    , 'NON-SCHOOL BUS': 'Bus'
    , 'NON-SCHOOL BUS (9 OCCUPANTS OR MORE INCLUDING DRIVER) IN COMMERCE': 'Bus'
    , 'MEDIUM/HEAVY TRUCKS GVWR/GCWR 16,001 AND OVER': 'Semi Truck'
    , 'MEDIUM/HEAVY TRUCKS GVWR/GCWR BETWEEN 10,001 AND 16,000': 'Semi Truck'
    , 'OFF HIGHWAY VEHICLE/ATV': 'Other'
    , 'MOTOR HOME': 'Other'
    , 'MOTORIZED BICYCLE': 'Motorcycle'
    , 'FARM EQUIPMENT': 'Other'
    , 'LOW SPEED VEHICLE': 'Other'
    , 'AUTOCYCLE': 'Motorcycle'
    , 'WORKING VEHICLE/EQUIPMENT': 'Other'
    , 'LIGHT RAIL': 'Other'
}

df['at_fault_vehicle'] = df['TU1_VEHICLE_TYPE_UPPER'].map(vehicle_type_mapping).fillna(df['TU1_VEHICLE_TYPE'])

In [7]:
df.groupby('TU1_VEHICLE_TYPE_UPPER').size()

TU1_VEHICLE_TYPE_UPPER
                                                                      2132
0                                                                        1
AUTOCYCLE                                                               29
BICYCLE                                                               1129
FARM EQUIPMENT                                                          24
HIT AND RUN UNKNOWN                                                  14704
LIGHT RAIL                                                              27
LOW SPEED VEHICLE                                                        8
MEDIUM/HEAVY TRUCKS GVWR/GCWR 16,001 AND OVER                          411
MEDIUM/HEAVY TRUCKS GVWR/GCWR BETWEEN 10,001 AND 16,000                210
MOTOR HOME                                                             174
MOTORCYCLE                                                            1461
MOTORIZED BICYCLE                                                       92
NON-SCHOOL BUS                                                         454
NON-SCHOOL BUS (9 OCCUPANTS OR MORE INCLUDING DRIVER) IN COMMERCE       25
OFF HIGHWAY VEHICLE/ATV                                                  5
OTHER                                                                 8118
OTHER VEHICLE TYPE (DESCRIBE IN NARATIVE)                               84
PASSENGER CAR/PASSENGER VAN                                           9422
PASSENGER CAR/VAN                                                    96848
PASSENGER CAR/VAN WITH TRAILER                                         361
PICKUP TRUCK/UTILITY VAN                                             24532
PICKUP TRUCK/UTILITY VAN WITH TRAILIER                                4680
SCHOOL BUS                                                             277
SCHOOL BUS (ALL SCHOOL BUSES)                                           33
SUV                                                                  47699
SUV WITH TRAILER                                                       178
TRANSIT BUS                                                            983
UNDER INVESTIGATION                                                    717
UNK                                                                      1
UNKNOWN (HIT AND RUN ONLY)                                            1555
VEHICLE OVER 10000 LBS                                                6323
WORKING VEHICLE/EQUIPMENT                                               48
dtype: int64

In [8]:
df.groupby('at_fault_vehicle').size().sort_values(ascending=False)

at_fault_vehicle
Passenger Car/Van             106631
SUV                            47877
Pickup Truck                   29212
Unknown (Hit and Run Only)     16259
Other                          10622
Semi Truck                      6944
Bus                             1772
Motorcycle                      1582
Bicycle                         1129
Under Investigation              717
dtype: int64

In [9]:
# pd.pivot_table(
#     data=df
#     , values='one'
#     , index=['at_fault_vehicle', 'TU1_VEHICLE_TYPE_UPPER']
#     , columns='crash_year'
#     , aggfunc='sum'
#     , fill_value=0
# )

In [10]:
at_fault_vehicle_pivot = pd.pivot_table(
    data=df
    , values='one'
    , index='at_fault_vehicle'
    , columns='crash_year'
    , aggfunc='sum'
    , fill_value=0
)

at_fault_vehicle_pivot.drop('Under Investigation', inplace=True)
at_fault_vehicle_pivot

crash_year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
at_fault_vehicle,,,,,,,,,,,
Bicycle,175,158,148,135,145,129,112,72,54,1,0
Bus,202,209,196,220,222,239,199,90,89,104,2
Motorcycle,158,152,167,178,165,154,138,134,177,158,1
Other,915,870,806,885,1226,1202,2436,791,828,658,5
Passenger Car/Van,11237,11776,12655,12678,12829,12223,10734,6839,7766,7592,302
Pickup Truck,2745,2898,3179,3315,3298,3444,3091,2346,2576,2246,74
SUV,3993,4636,5217,5330,5456,5573,5521,3739,4459,3788,165
Semi Truck,642,722,742,806,760,841,865,543,552,453,18
Unknown (Hit and Run Only),1550,1687,1682,1887,1792,1736,1745,1338,1568,1238,36

In [11]:
at_fault_vehicle_perc = at_fault_vehicle_pivot / at_fault_vehicle_pivot.sum(axis=0)
at_fault_vehicle_perc.style.format('{:.1%}').background_gradient()

In [12]:
# at_fault_vehicle_perc.transpose().plot(kind='bar', stacked=True)

## Conclusion

This data does not appear to be populating correctly in 2022 :(

In [13]:
df[df.incident_id == 2022165626].squeeze()

shape                            <geoprocessing describe geometry object object...
object_id                                                                      843
incident_id                                                             2022165626
offense_id                                                         202216562654410
offense_code                                                                  5441
offense_code_extension                                                           0
top_traffic_accident_offense                        TRAF - ACCIDENT
first_occurrence_date                                          2022-04-04 15:00:00
last_occurrence_date                                           2022-04-04 15:00:00
reported_date                                            2022-04-04 15:16:00-06:00
incident_address                                         N GAYLORD ST / E 18TH AVE
geo_x                                                                    3151566.0
geo_y                                                                    1696624.0
geo_lon                                                                -104.961005
geo_lat                                                                  39.744803
district_id                                                                 6
precinct_id                                                                  622.0
neighborhood_id                                                     City Park West
bicycle_ind                                                                    0.0
pedestrian_ind                                                                 0.0
HARMFUL_EVENT_SEQ_1                                                  Front to Side
HARMFUL_EVENT_SEQ_2                                                            NaN
HARMFUL_EVENT_SEQ_MOST                                               Front to Side
road_location                                                           On Roadway
ROAD_DESCRIPTION                                                   At Intersection
ROAD_CONTOUR                                                      Straight - Level
ROAD_CONDITION                                                                 Dry
LIGHT_CONDITION                                                           Daylight
TU1_VEHICLE_TYPE                                       Passenger Car/Passenger Van
TU1_TRAVEL_DIRECTION                                                         North
TU1_VEHICLE_MOVEMENT                                                Going Straight
TU1_DRIVER_ACTION                                              Failed to Yield ROW
TU1_DRIVER_HUMANCONTRIBFACTOR                            Distracted/Other Interior
TU1_PEDESTRIAN_ACTION                                                          NaN
TU2_VEHICLE_TYPE                                                               SUV
TU2_TRAVEL_DIRECTION                                                          West
TU2_VEHICLE_MOVEMENT                                                Going Straight
TU2_DRIVER_ACTION                                           No Contributing Action
TU2_DRIVER_HUMANCONTRIBFACTOR                      No Apparent Contributing Factor
TU2_PEDESTRIAN_ACTION                                                          NaN
SERIOUSLY_INJURED                                                              0.0
FATALITIES                                                                     0.0
FATALITY_MODE_1                                                                NaN
FATALITY_MODE_2                                                                NaN
SERIOUSLY_INJURED_MODE_1                                                       NaN
SERIOUSLY_INJURED_MODE_2                                                       NaN
POINT_X                                                                        NaN
POINT_Y                                                                        NaN
sbi                                                                          False
fatality                                                                     False
sbi_or_fatality                                                              False
crash_date                                                              2022-04-04
crash_date_str                                                      2022-04-04 Mon
crash_time_str                                                  Mon Apr 4, 3:16 PM
crash_year                                                                    2022
crash_day_of_year                                                               94
one                                                                              1
TU1_VEHICLE_TYPE_UPPER                                 PASSENGER CAR/PASSENGER VAN
at_fault_vehicle                                                 Passenger Car/Van
Name: 4768, dtype: object