# Vehicle Type

What sort of vehicles are involved in these crashes?

In [2]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib._color_data import BASE_COLORS, TABLEAU_COLORS, CSS4_COLORS, XKCD_COLORS
from crash_data_analysis import CrashDataAnalysis

In [3]:
cda = CrashDataAnalysis()
df = cda.crash_dataframe(verbose=True)

Reading file: data/denver_crashes_2022_05_25__09_00.csv
Max timestamp: 2022-05-23 21:19:00

In [6]:
df.groupby('TU1_VEHICLE_TYPE').size()

TU1_VEHICLE_TYPE
                                           2132
0                                             1
BICYCLE                                    1129
FARM EQUIPMENT                               23
HIT AND RUN UNKNOWN                       14709
LIGHT RAIL                                   27
MOTOR HOME                                  150
MOTORCYCLE                                 1302
MOTORIZED BICYCLE                            92
NON-SCHOOL BUS                              454
OTHER                                     17867
PASSENGER CAR/VAN                         96877
PASSENGER CAR/VAN WITH TRAILER              361
PICKUP TRUCK/UTILITY VAN                  21647
PICKUP TRUCK/UTILITY VAN WITH TRAILIER     4681
SCHOOL BUS                                  277
SUV                                       42701
SUV WITH TRAILER                            179
TRANSIT BUS                                 909
UNDER INVESTIGATION                         602
UNK                                           1
VEHICLE OVER 10000 LBS                     6328
dtype: int64

In [10]:
pd.pivot_table(
    data=df
    , values='one'
    , index='TU1_VEHICLE_TYPE'
    , columns='crash_year'
    , aggfunc='sum'
    , fill_value=0
)

crash_year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
TU1_VEHICLE_TYPE,,,,,,,,,,
,638,592,543,352,6,1,0,0,0,0
0,0,0,0,0,1,0,0,0,0,0
BICYCLE,175,158,148,135,145,129,112,72,54,1
FARM EQUIPMENT,6,3,5,1,0,4,1,1,2,0
HIT AND RUN UNKNOWN,1550,1687,1682,1887,1792,1736,1745,1338,1275,17
LIGHT RAIL,1,5,3,4,2,6,2,1,3,0
MOTOR HOME,9,11,25,13,18,26,18,16,14,0
MOTORCYCLE,141,143,160,167,160,146,125,120,140,0
MOTORIZED BICYCLE,17,9,7,11,5,8,13,14,8,0
NON-SCHOOL BUS,57,50,59,58,67,66,58,21,18,0
OTHER,261,259,230,515,1198,1165,2413,771,4964,6091
PASSENGER CAR/VAN,11198,11721,12610,12632,12796,12179,10692,6804,6140,105
PASSENGER CAR/VAN WITH TRAILER,39,55,45,46,33,44,42,35,20,2
PICKUP TRUCK/UTILITY VAN,2318,2440,2680,2665,2682,2808,2564,1915,1552,23
PICKUP TRUCK/UTILITY VAN WITH TRAILIER,427,458,499,650,616,636,527,431,424,13
SCHOOL BUS,43,46,36,41,40,31,25,10,5,0
SUV,3981,4620,5199,5308,5432,5552,5495,3724,3344,46
SUV WITH TRAILER,12,16,18,22,24,21,26,15,24,1
TRANSIT BUS,102,113,101,121,115,142,116,59,40,0
UNDER INVESTIGATION,0,1,4,0,7,36,40,39,37,438
UNK,0,0,0,0,1,0,0,0,0,0
VEHICLE OVER 10000 LBS,642,722,742,806,760,841,865,543,401,6

In [11]:
pd.pivot_table(
    data=df
    , values='one'
    , index='TU2_VEHICLE_TYPE'
    , columns='crash_year'
    , aggfunc='sum'
    , fill_value=0
)

crash_year,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
TU2_VEHICLE_TYPE,,,,,,,,,,
,2494,2559,2459,1428,6,1,0,0,1,0
BICYCLE,142,164,189,170,168,173,146,106,61,1
FARM EQUIPMENT,1,1,0,1,3,1,3,2,3,0
HIT AND RUN UNKNOWN,48,59,42,56,58,63,66,43,48,0
LIGHT RAIL,11,21,11,7,5,7,8,4,3,0
MOTOR HOME,3,9,3,11,6,9,10,12,6,1
MOTORCYCLE,159,172,171,176,157,180,148,127,116,2
MOTORIZED BICYCLE,14,11,10,11,6,10,5,5,7,1
NON-SCHOOL BUS,63,78,81,59,73,81,80,23,21,0
OTHER,243,232,235,1218,2896,2741,3983,2203,6146,6124
PASSENGER CAR/VAN,11186,11717,12422,13216,12925,12430,10839,6627,5941,99
PASSENGER CAR/VAN WITH TRAILER,64,53,42,53,45,46,48,32,31,1
PICKUP TRUCK/UTILITY VAN,2060,2132,2408,2304,2443,2406,2344,1779,1477,17
PICKUP TRUCK/UTILITY VAN WITH TRAILIER,319,349,453,468,547,555,498,330,344,4
SCHOOL BUS,62,43,41,36,35,35,24,7,12,0
SUV,4114,4747,5453,5447,5773,6082,5884,4124,3819,49
SUV WITH TRAILER,9,25,27,27,23,26,8,6,14,0
TRANSIT BUS,164,192,165,151,162,136,137,73,49,1
UNDER INVESTIGATION,0,1,4,0,7,36,40,39,37,438
VEHICLE OVER 10000 LBS,461,544,580,595,562,559,608,387,329,5

## Conclusion

This data does not appear to be populating correctly in 2022 :(

In [13]:
df[df.incident_id == 2022165626].squeeze()

incident_id                                          2022165626
offense_id                                      202216562654410
offense_code                                             5441.0
offense_code_extension                                      0.0
top_traffic_accident_offense     TRAF - ACCIDENT
first_occurrence_date                       2022-04-04 15:00:00
last_occurrence_date                        2022-04-04 15:00:00
reported_date                               2022-04-04 15:16:00
incident_address                      N GAYLORD ST / E 18TH AVE
geo_x                                                 3151566.0
geo_y                                                 1696624.0
geo_lon                                             -104.961005
geo_lat                                               39.744803
district_id                                              6
precinct_id                                               622.0
neighborhood_id                                  City Park West
bicycle_ind                                                 NaN
pedestrian_ind                                              NaN
HARMFUL_EVENT_SEQ_1
HARMFUL_EVENT_SEQ_2
HARMFUL_EVENT_SEQ_3
road_location
ROAD_DESCRIPTION
ROAD_CONTOUR
ROAD_CONDITION
LIGHT_CONDITION
TU1_VEHICLE_TYPE                                          OTHER
TU1_TRAVEL_DIRECTION                                      OTHER
TU1_VEHICLE_MOVEMENT                                      OTHER
TU1_DRIVER_ACTION                                         OTHER
TU1_DRIVER_HUMANCONTRIBFACTOR                             OTHER
TU1_PEDESTRIAN_ACTION                                     OTHER
TU2_VEHICLE_TYPE                                          OTHER
TU2_TRAVEL_DIRECTION                                      OTHER
TU2_VEHICLE_MOVEMENT                                      OTHER
TU2_DRIVER_ACTION                                         OTHER
TU2_DRIVER_HUMANCONTRIBFACTOR                             OTHER
TU2_PEDESTRIAN_ACTION                                     OTHER
SERIOUSLY_INJURED                                           0.0
FATALITIES                                                  0.0
FATALITY_MODE_1                                           OTHER
FATALITY_MODE_2                                           OTHER
SERIOUSLY_INJURED_MODE_1                                  OTHER
SERIOUSLY_INJURED_MODE_2                                  OTHER
POINT_X                                                     NaN
POINT_Y                                                     NaN
sbi                                                       False
fatality                                                  False
sbi_or_fatality                                           False
crash_date_str                                   2022-04-04 Mon
crash_time_str                               Mon Apr 4, 3:16 PM
crash_year                                                 2022
crash_day_of_year                                            94
one                                                           1
Name: 211912, dtype: object