# Vehicle Type

What sort of vehicles are involved in these crashes?

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib._color_data import BASE_COLORS, TABLEAU_COLORS, CSS4_COLORS, XKCD_COLORS
from crash_data_analysis import CrashDataAnalysis

In [2]:
df = pd.read_csv('data/raw_crash_data.csv', low_memory=False)

In [3]:
df.TU1_VEHICLE_TYPE.unique()

array(['UNDER INVESTIGATION', 'Pickup Truck/Utility Van', nan,
       'Unknown (Hit and Run Only)', 'SUV', 'Passenger Car/Passenger Van',
       'Medium/Heavy Trucks GVWR/GCWR 16,001 and over', 'Motorcycle',
       'Other Vehicle Type (Describe in Narative)', 'Transit Bus',
       'School Bus (all school buses)', 'Motor Home',
       'Medium/Heavy Trucks GVWR/GCWR between 10,001 and 16,000',
       'Working Vehicle/Equipment', 'Autocycle',
       'Non-School Bus (9 occupants or more including driver) in commerce',
       'Low Speed Vehicle', 'Off Highway Vehicle/ATV', 'Farm Equipment',
       'OTHER', 'PASSENGER CAR/VAN', 'PICKUP TRUCK/UTILITY VAN',
       'VEHICLE OVER 10000 LBS', 'HIT AND RUN UNKNOWN', 'BICYCLE',
       'FARM EQUIPMENT', 'TRANSIT BUS', 'MOTORCYCLE',
       'PICKUP TRUCK/UTILITY VAN WITH TRAILIER',
       'PASSENGER CAR/VAN WITH TRAILER', 'SCHOOL BUS', 'SUV WITH TRAILER',
       'NON-SCHOOL BUS', 'MOTOR HOME', 'LIGHT RAIL', 'MOTORIZED BICYCLE',
       '  ', '0', 'UNK'], dtype=object)

In [4]:
df.TU1_VEHICLE_MOVEMENT.unique()

array(['UNDER INVESTIGATION', 'Entering Traffic Way/Merge', nan,
       'Making Right Turn', 'Going Straight', 'Negotiating a Curve',
       'Entering/Leaving Parked Position', 'Slowing', 'Backing',
       'Changing Lanes', 'Making Left Turn', 'Swerve/Avoidance',
       'Other (Describe in Narrative)', 'Weaving', 'Out of Control',
       'Making U-Turn', 'Passing', 'Stopped in Traffic', 'Parked',
       'Traveled Wrong Way', 'OTHER', 'GOING STRAIGHT', 'BACKING',
       'SLOWING', 'MAKING RIGHT TURN', 'MAKING LEFT TURN', 'PASSING',
       'PARKED', 'SPUN OUT OF CONTROL', 'CHANGING LANES', 'MAKING U-TURN',
       'ENTERING/LEAVING PARKED POSITION', 'AVOIDING OBJECT IN ROADWAY',
       'STOPPED IN TRAFFIC', 'WEAVING', 'DROVE WRONG WAY', '  ', '18',
       '021', '00'], dtype=object)

In [5]:
# df['at_fault_vehicle'] = df['TU1_VEHICLE_TYPE']

# otherize = ['  ', '0', 'UNK']
# for v in otherize:
#     df.loc[df.TU1_VEHICLE_TYPE == v, 'at_fault_vehicle'] = 'Other'

In [6]:
df['TU1_VEHICLE_TYPE_UPPER'] = df['TU1_VEHICLE_TYPE'].str.upper()

vehicle_type_mapping = {
    '  ': 'Other'
    , '0': 'Other'
    , 'UNK': 'Other'
    , 'OTHER VEHICLE TYPE (DESCRIBE IN NARATIVE)': 'Other'
    , 'OTHER': 'Other'
    , 'SUV WITH TRAILER': 'SUV'
    , 'PASSENGER CAR/VAN': 'Passenger Car/Van'
    , 'PASSENGER CAR/VAN WITH TRAILER': 'Passenger Car/Van'
    , 'PASSENGER CAR/PASSENGER VAN': 'Passenger Car/Van'
    , 'SCHOOL BUS': 'Bus'
    , 'SCHOOL BUS (ALL SCHOOL BUSES)': 'Bus'
    , 'TRANSIT BUS': 'Bus'
    , 'HIT AND RUN UNKNOWN': 'Unknown (Hit and Run Only)'
    , 'PICKUP TRUCK/UTILITY VAN': 'Pickup Truck'
    , 'PICKUP TRUCK/UTILITY VAN WITH TRAILIER': 'Pickup Truck'
    , 'VEHICLE OVER 10000 LBS': 'Semi Truck'
    , 'MOTORCYCLE': 'Motorcycle'
    , 'BICYCLE': 'Bicycle'
    , 'UNDER INVESTIGATION': 'Under Investigation'
    , 'NON-SCHOOL BUS': 'Bus'
    , 'NON-SCHOOL BUS (9 OCCUPANTS OR MORE INCLUDING DRIVER) IN COMMERCE': 'Bus'
    , 'MEDIUM/HEAVY TRUCKS GVWR/GCWR 16,001 AND OVER': 'Semi Truck'
    , 'MEDIUM/HEAVY TRUCKS GVWR/GCWR BETWEEN 10,001 AND 16,000': 'Semi Truck'
    , 'OFF HIGHWAY VEHICLE/ATV': 'Other'
    , 'MOTOR HOME': 'Other'
    , 'MOTORIZED BICYCLE': 'Motorcycle'
    , 'FARM EQUIPMENT': 'Other'
    , 'LOW SPEED VEHICLE': 'Other'
    , 'AUTOCYCLE': 'Motorcycle'
    , 'WORKING VEHICLE/EQUIPMENT': 'Other'
    , 'LIGHT RAIL': 'Other'
}

df['at_fault_vehicle'] = df['TU1_VEHICLE_TYPE_UPPER'].map(vehicle_type_mapping).fillna(df['TU1_VEHICLE_TYPE'])

In [7]:
df.groupby('TU1_VEHICLE_TYPE_UPPER').size()

TU1_VEHICLE_TYPE_UPPER
                                                                      2132
0                                                                        1
AUTOCYCLE                                                               33
BICYCLE                                                               1129
FARM EQUIPMENT                                                          24
HIT AND RUN UNKNOWN                                                  14704
LIGHT RAIL                                                              27
LOW SPEED VEHICLE                                                        9
MEDIUM/HEAVY TRUCKS GVWR/GCWR 16,001 AND OVER                          504
MEDIUM/HEAVY TRUCKS GVWR/GCWR BETWEEN 10,001 AND 16,000                248
MOTOR HOME                                                             180
MOTORCYCLE                                                            1476
MOTORIZED BICYCLE                                                       92
NON-SCHOOL BUS                                                         454
NON-SCHOOL BUS (9 OCCUPANTS OR MORE INCLUDING DRIVER) IN COMMERCE       31
OFF HIGHWAY VEHICLE/ATV                                                  5
OTHER                                                                 8117
OTHER VEHICLE TYPE (DESCRIBE IN NARATIVE)                               96
PASSENGER CAR/PASSENGER VAN                                          11251
PASSENGER CAR/VAN                                                    96849
PASSENGER CAR/VAN WITH TRAILER                                         361
PICKUP TRUCK/UTILITY VAN                                             25029
PICKUP TRUCK/UTILITY VAN WITH TRAILIER                                4680
SCHOOL BUS                                                             277
SCHOOL BUS (ALL SCHOOL BUSES)                                           37
SUV                                                                  48601
SUV WITH TRAILER                                                       178
TRANSIT BUS                                                            999
UNDER INVESTIGATION                                                    787
UNK                                                                      1
UNKNOWN (HIT AND RUN ONLY)                                            1841
VEHICLE OVER 10000 LBS                                                6323
WORKING VEHICLE/EQUIPMENT                                               57
dtype: int64

In [8]:
df.groupby('at_fault_vehicle').size().sort_values(ascending=False)

at_fault_vehicle
Passenger Car/Van             108461
SUV                            48779
Pickup Truck                   29709
Unknown (Hit and Run Only)     16545
Other                          10649
Semi Truck                      7075
Bus                             1798
Motorcycle                      1601
Bicycle                         1129
Under Investigation              787
dtype: int64

In [9]:
# pd.pivot_table(
#     data=df
#     , values='one'
#     , index=['at_fault_vehicle', 'TU1_VEHICLE_TYPE_UPPER']
#     , columns='crash_year'
#     , aggfunc='sum'
#     , fill_value=0
# )

In [10]:
df['one'] = 1
df['reported_date'] = pd.to_datetime(df['reported_date'], format='mixed')

at_fault_vehicle_pivot = pd.pivot_table(
    data=df
    , values='one'
    , index='at_fault_vehicle'
    , columns=df.reported_date.dt.year
    , aggfunc='sum'
    , fill_value=0
)

at_fault_vehicle_pivot.drop('Under Investigation', inplace=True)
at_fault_vehicle_pivot

reported_date,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
at_fault_vehicle,,,,,,,,,,,
Bicycle,175,158,148,135,145,129,112,72,54,1,0
Bus,202,209,196,220,222,239,199,90,89,104,28
Motorcycle,158,152,167,178,165,154,138,134,177,157,21
Other,915,870,806,885,1226,1202,2436,791,828,659,31
Passenger Car/Van,11237,11776,12655,12678,12829,12223,10734,6839,7767,7644,2079
Pickup Truck,2745,2898,3179,3315,3298,3444,3091,2346,2576,2275,542
SUV,3993,4636,5217,5330,5456,5573,5521,3739,4459,3816,1039
Semi Truck,642,722,742,806,760,841,865,543,552,461,141
Unknown (Hit and Run Only),1550,1687,1682,1887,1792,1736,1745,1338,1568,1249,311

In [11]:
at_fault_vehicle_perc = at_fault_vehicle_pivot / at_fault_vehicle_pivot.sum(axis=0)

at_fault_vehicle_perc.style.format('{:.1%}').background_gradient(cmap='Reds')

In [12]:
# at_fault_vehicle_perc.transpose().plot(kind='bar', stacked=True)

## Conclusion

This data is now populating correctly in 2022 :)

In [13]:
df[df.incident_id == 2022165626].squeeze()

shape                            <geoprocessing describe geometry object object...
object_id                                                                      843
incident_id                                                             2022165626
offense_id                                                         202216562654410
offense_code                                                                  5441
offense_code_extension                                                           0
top_traffic_accident_offense                        TRAF - ACCIDENT
first_occurrence_date                                          2022-04-04 15:00:00
last_occurrence_date                                           2022-04-04 15:00:00
reported_date                                                  2022-04-04 15:16:00
incident_address                                         N GAYLORD ST / E 18TH AVE
geo_x                                                                    3151566.0
geo_y                                                                    1696624.0
geo_lon                                                                -104.961005
geo_lat                                                                  39.744803
district_id                                                                 6
precinct_id                                                                  622.0
neighborhood_id                                                     City Park West
bicycle_ind                                                                    0.0
pedestrian_ind                                                                 0.0
HARMFUL_EVENT_SEQ_1                                                  Front to Side
HARMFUL_EVENT_SEQ_2                                                            NaN
HARMFUL_EVENT_SEQ_MOST                                               Front to Side
road_location                                                           On Roadway
ROAD_DESCRIPTION                                                   At Intersection
ROAD_CONTOUR                                                      Straight - Level
ROAD_CONDITION                                                                 Dry
LIGHT_CONDITION                                                           Daylight
TU1_VEHICLE_TYPE                                       Passenger Car/Passenger Van
TU1_TRAVEL_DIRECTION                                                         North
TU1_VEHICLE_MOVEMENT                                                Going Straight
TU1_DRIVER_ACTION                                              Failed to Yield ROW
TU1_DRIVER_HUMANCONTRIBFACTOR                            Distracted/Other Interior
TU1_PEDESTRIAN_ACTION                                                          NaN
TU2_VEHICLE_TYPE                                                               SUV
TU2_TRAVEL_DIRECTION                                                          West
TU2_VEHICLE_MOVEMENT                                                Going Straight
TU2_DRIVER_ACTION                                           No Contributing Action
TU2_DRIVER_HUMANCONTRIBFACTOR                      No Apparent Contributing Factor
TU2_PEDESTRIAN_ACTION                                                          NaN
SERIOUSLY_INJURED                                                              0.0
FATALITIES                                                                     0.0
FATALITY_MODE_1                                                                NaN
FATALITY_MODE_2                                                                NaN
SERIOUSLY_INJURED_MODE_1                                                       NaN
SERIOUSLY_INJURED_MODE_2                                                       NaN
POINT_X                                                                        NaN
POINT_Y                                                                        NaN
updated_at                                        2023-04-14T21:25:50.626224+00:00
TU1_VEHICLE_TYPE_UPPER                                 PASSENGER CAR/PASSENGER VAN
at_fault_vehicle                                                 Passenger Car/Van
one                                                                              1
Name: 4166, dtype: object

In [17]:
df.groupby('TU2_VEHICLE_TYPE').size().sort_values(ascending=False)

TU2_VEHICLE_TYPE
PASSENGER CAR/VAN                                                    97377
SUV                                                                  51974
PICKUP TRUCK/UTILITY VAN                                             19363
OTHER                                                                16268
Passenger Car/Passenger Van                                          11802
                                                                      8948
VEHICLE OVER 10000 LBS                                                4630
PICKUP TRUCK/UTILITY VAN WITH TRAILIER                                3866
Pickup Truck/Utility Van                                              3060
MOTORCYCLE                                                            1409
BICYCLE                                                               1319
TRANSIT BUS                                                           1229
UNDER INVESTIGATION                                                    787
NON-SCHOOL BUS                                                         559
HIT AND RUN UNKNOWN                                                    483
PASSENGER CAR/VAN WITH TRAILER                                         415
Medium/Heavy Trucks GVWR/GCWR 16,001 and over                          370
SCHOOL BUS                                                             295
SUV WITH TRAILER                                                       165
Medium/Heavy Trucks GVWR/GCWR between 10,001 and 16,000                148
Motorcycle                                                             148
Transit Bus                                                            142
Other Vehicle Type (Describe in Narative)                              105
MOTORIZED BICYCLE                                                       80
LIGHT RAIL                                                              77
MOTOR HOME                                                              70
Working Vehicle/Equipment                                               56
Unknown (Hit and Run Only)                                              47
Non-School Bus (9 occupants or more including driver) in commerce       46
School Bus (all school buses)                                           31
Autocycle                                                               26
FARM EQUIPMENT                                                          15
Motor Home                                                               8
Low Speed Vehicle                                                        7
Light Rail                                                               5
Heavy Train                                                              4
Farm Equipment                                                           3
Snowmobile                                                               1
dtype: int64